//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTYService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityFornecedor
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Estado { get; set; }
        public string Cidade { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Demanda { get; set; }
        public System.DateTime Vigencia { get; set; }
    
        public virtual EntityContato contato { get; set; }
    }
}
